### ISSUE TITLE
Лог демона speedtest

### ISSUE THREAD

**Issue by ARTIsshoque** [bis-gmbh/2ip-speed#2]
Добрый день.
Третьи сутки подряд самопроизвольно отключается демон speedtest. Для диагностики проблемы хотелось бы посмотреть лог. Запускаю демон командой:
/usr/bin/speedtest --certdir=/etc/letsencrypt/live/{server.domain} --port=8001 --log=true --debug=true &
В syslog новых записей не появляется. Отдельного лог-файла тоже не нашёл. Подскажите, пожалуйста, где искать лог демона speedtest.

**Comment by glushchenko** [comment]
Мы выпустили спидометр v2, думаю проблема с подробным логом решена.
