### ISSUE TITLE
После обновления

### ISSUE THREAD

**Issue by gabalino** [bis-gmbh/2ip-speed#3]
После обновления не запускается сервис на CentOS 7, подскажите, как решить эту проблему?

Jul 28 18:27:23 speed systemd[1]: 2ip-speed.service holdoff time over, scheduling restart.
Jul 28 18:27:23 speed systemd[1]: Started 2ip speed.
Jul 28 18:27:23 speed systemd[1]: Starting 2ip speed...
Jul 28 18:27:23 speed speedtest: 2018/07/28 18:27:23 LetsEncrypt verification port binding failed. Port 80 available only for root user.
Jul 28 18:27:23 speed systemd[1]: 2ip-speed.service: main process exited, code=exited, status=1/FAILURE
Jul 28 18:27:23 speed systemd[1]: Unit 2ip-speed.service entered failed state.
Jul 28 18:27:23 speed systemd[1]: 2ip-speed.service failed.

**Comment by glushchenko** [comment]
Откройте 80 порт.

**Comment by gabalino** [comment]
@glushchenko 80-й порт открыт

**Comment by glushchenko** [comment]
И на нём висит nginx? Демон не может забиндить порт, либо прав нет, либо он уже занят, других вариантов в принципе и нет.

**Comment by gabalino** [comment]
nginx остановлен, порт не используется. Демон запускается от пользователя nobody, как повысить права на биндинг?

**Comment by glushchenko** [comment]
Спасибо за фидбек. Действительно была проблема в конфигурации systemd для использования на 80 порту. Добавил конфигурацию сокета и исправил демон. В последней версии все хорошо, пробуйте.

**Comment by gabalino** [comment]
@glushchenko 
Подскажите, как использовать совместно с Nginx?

**Comment by glushchenko** [comment]
Никак, 80 порт занят

**Comment by glushchenko** [comment]
В последней версии выпилили необходимость 80 порта
