### ISSUE TITLE
SIGSEGV on FreeBSD

### ISSUE THREAD

**Issue by asb-72** [bis-gmbh/2ip-speed#5]
Последнее время начал падать с такими сообщениями:

2022/09/14 20:02:26 2ip speed server started on port: 8002 🍺
Get https://2ip.ru/?area=certUpdater&type=crt: read tcp x.x.16.6:49807->195.201.201.32:443: read: connection reset by peerpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6ca33f]

goroutine 1 [running]:
main.load(0x77aa68, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/fluder/src/2ip/dockerfiles/speedtest/main.go:217 +0x12f
main.(*wrappedCertificate).updateCert(0xc000074d70, 0x0, 0x0)
	/Users/fluder/src/2ip/dockerfiles/speedtest/main.go:187 +0xaf
main.main()
	/Users/fluder/src/2ip/dockerfiles/speedtest/main.go:64 +0x1f4

**Comment by glushchenko** [comment]
Привет, попробуйте сделать `curl https://2ip.ru`, если будет ошибка, то вам нужно будет обновить корневые сертификаты в системе. Демон не дает к нам законнектиться из-за протухших сертификатов.

**Comment by asb-72** [comment]
Добрый день.
С сертификатами вроде все нормально, но периодически коннект не проходит и отваливается по таймауту, либо прилетает RST от сервера.
Выше как раз паника из-за RST.

вот два варианта ответов:
1.
`curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to 2ip.ru:443 
`
2.
```curl -v https://2ip.ru
*   Trying 195.201.201.32:443...
* Connected to 2ip.ru (195.201.201.32) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /usr/local/share/certs/ca-root-nss.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=2ip.ru
*  start date: Aug 23 08:52:30 2022 GMT
*  expire date: Nov 21 08:52:29 2022 GMT
*  subjectAltName: host "2ip.ru" matched cert's "2ip.ru"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: 2ip.ru
> User-Agent: curl/7.85.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx
< Date: Mon, 19 Sep 2022 06:08:20 GMT
< Content-Type: application/octet-stream
< Content-Length: 11
< Connection: keep-alive
< 
```

**Comment by glushchenko** [comment]
Проблема не в коннекте, а именно в корневом сертификате для letsencrypt. Детали тут https://www.cyberciti.biz/faq/freebsd-wget-cannot-verify-certificate-issued-by-lets-encrypt/

**Comment by asb-72** [comment]
А где в сообщении "curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to 2ip.ru:443" написано про сертификат?

Но это ладно, 2ip.ru вроде попустило и коннект от принимает, на запрос "curl https://2ip.ru" возвращает мой адрес.

Но все равно падает с сообщением из первого поста. Причем если запросить "https://2ip.ru/?area=certUpdater&type=crt" curl'ом, то сервер возвращает страничку с 
```
2ip.ru | Anti-DDoS</h1>
<p>
<br>
<!-- Start: Ad code and script tags for top of page -->
<!-- End: Ad code and script tags for top of page -->
<br>
<center>
<br>
<div id="status" style="color:#bd2426;font-size:130%; border: 1px dashed gray; border-radius: 15px; padding: 30px; max-width: 700px; ">
<noscript>Please turn JavaScript on and reload the page.<br></noscript>
Please wait a moment while we verify your request.<br>
This process is automatic. Your browser will redirect to your requested content shortly.<br>
<br>
<span style="color: #85144b">
<noscript>Вам необходимо включить JavaScript и перезагрузить страницу.<br></noscript>
Пожалуйста, подождите несколько секунд, пока мы верифицируем ваш запрос.<br>
Ваш браузер будет перенаправлен к содержимому сайта скоренько.</span>
<br>

```

Да и во втором варианте сервер отвечал:
```
HTTP/1.1 200 OK
< Server: nginx
```
как интересно он это ответил если проблема в сетификате? Ответ простой - не в сертификате дело, а в обработке ошибок в приложении, либо настройках со стороны 2ip

**Comment by glushchenko** [comment]
Ваша ошибка не имеет никакого отношения к первоначальному вопросу. Был недоступен наш сервер, уже починили.

**Comment by asb-72** [comment]
Сейчас запускается нормально, спасибо. 
Но падать с sigsegv при недоступном сервере - это, мягко говоря, странно.
